### ISSUE TITLE
Mistake found in step 7

### ISSUE THREAD

**Issue by ninaszymor** [raspberrypilearning/cd-advanced-html-css-sushi#11]
A Dutch volunteer noticed some inconsistencies in Step 7 when translating the project:

- The section **Pictures with captions** contains the following sentence: *On a new line below the code, place the closing tag <\figure>*. It uses a backslash instead of a forward slash.
- The section **Side Notes** contains a sentence: *Outside of the `article` element, add one or more pairs of <aside><\aside> tags containing your extra stuff*. Again, a back slash instead of forward slash is used.

**Comment by CiaraMcHugh** [comment]
This has been fixed now, thanks for raising it @ninaszymor 
See PR #16
